export enum EventEnum {
  EVENT_LOOP_START,
  EVENT_LOOP_END,
  EVENT_KEY_UP,
  EVENT_KEY_DOWN,
  EVENT_KEY_PRESS,
  EVENT_MOUSE_DOWN,
  EVENT_MOUSE_UP,
  EVENT_MOUSE_MOVE,
  EVENT_MOUSE_CLICK,
  EVENT_GAME_END,
}
