export const enum SceneEventEnums {
  SCENE_FRAME_START = "SCENE_FRAME_START",
  SCENE_FRAME_END = "SCENE_FRAME_END",
  SCENE_UPDATE_START = "SCENE_UPDATE_START",
  SCENE_UPDATE_END = "SCENE_UPDATE_END",
  SCENE_RENDER_START = "SCENE_RENDER_START",
  SCENE_RENDER_END = "SCENE_RENDER_END",
}
